name: Workflow Events

on:                                       # the object structure allows us customize easily
    pull_request:
    workflow_dispatch:    # enable me to trigger the workflow from the U.I


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: Show the trigger
            run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
